source 'https://rubygems.org'
ruby '2.2.0'

gem 'middleman', '~> 4.4.0'
gem 'middleman-livereload', '~> 3.4.2'
gem 'middleman-autoprefixer'
gem 'middleman-minify-html'
gem 'middleman-syntax', '>= 2.1.0'
gem 'middleman-s3_sync'
gem 'middleman-search_engine_sitemap', '>= 1.4.0'

gem 'slim'
gem 'therubyracer'
gem 'oj'
gem 'redcarpet', '>= 3.5.1'
gem 'travis'
gem 'nokogiri', '>= 1.13.9'
gem 'rainbow'
gem "bootstrap-sass", ">= 3.4.0", require: false

platforms :mswin, :mingw do
  gem 'tzinfo-data'
  gem 'wdm', '~> 0.1.0'
end
